<?php

/* @see _renderkit8_pop_parent() */

use Drupal\faktoria\Hub\CfrPluginDiscoveryHub;

define('RENDERKIT_POP_PARENT', '_renderkit8_pop_parent');

/**
 * Implements hook_cfrplugin_info()
 *
 * @return array
 */
function renderkit8_cfrplugin_info() {

  return function_exists('cfrplugindiscovery')
    ? cfrplugindiscovery()->discoverByInterface(__DIR__ . '/src', 'Drupal\renderkit8')
    : [];
}

/**
 * Implements hook_faktoria_info()
 *
 * @return array
 */
function renderkit8_faktoria_info() {
  return CfrPluginDiscoveryHub::getInstance()
    ->moduleFileScanPsr4(__FILE__);
}

/**
 * @param array $element
 *
 * @return array
 */
function _renderkit8_pop_parent(array $element) {
  array_pop($element['#parents']);
  return $element;
}

/**
 * @param array $existing_form
 * @param array $form_state
 * @param array $form
 *
 * @return array
 */
function _renderkit8_generic_form(
  /** @noinspection PhpUnusedParameterInspection */ array $existing_form,
  /** @noinspection PhpUnusedParameterInspection */ array &$form_state,
  array $form
) {
  return $form;
}
