<?php
declare(strict_types=1);

/* @see _renderkit_pop_parent() */

use Drupal\faktoria\Hub\CfrPluginDiscoveryHub;

define('RENDERKIT_POP_PARENT', '_renderkit_pop_parent');

/**
 * Implements hook_cfrplugin_info()
 *
 * @return array
 */
function renderkit_cfrplugin_info(): array {

  return function_exists('cfrplugindiscovery')
    ? cfrplugindiscovery()->discoverByInterface(__DIR__ . '/src', 'Drupal\renderkit')
    : [];
}

/**
 * Implements hook_faktoria_info()
 *
 * @return array
 */
function renderkit_faktoria_info(): array {
  return CfrPluginDiscoveryHub::getInstance()
    ->moduleFileScanPsr4(__FILE__);
}

/**
 * @param array $element
 *
 * @return array
 */
function _renderkit_pop_parent(array $element): array {
  array_pop($element['#parents']);
  return $element;
}

/**
 * @param array $existing_form
 * @param array $form_state
 * @param array $form
 *
 * @return array
 */
function _renderkit_generic_form(
  /** @noinspection PhpUnusedParameterInspection */ array $existing_form,
  /** @noinspection PhpUnusedParameterInspection */ array &$form_state,
  array $form
): array {
  return $form;
}
