<?php

declare(strict_types=1);

namespace Drupal\service_discovery_test;

use Drupal\service_discovery\ModuleServiceProviderBase;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class ServiceDiscoveryTestServiceProvider extends ModuleServiceProviderBase {

  public function register(ContainerBuilder $container): void {
    parent::register($container); // TODO: Change the autogenerated stub
  }

}
