<?php
declare(strict_types=1);

/**
 * Implements hook_theme()
 *
 * @return array[]
 */
function themekit_theme(): array {
  return [
    //  This theme hook made sense in Drupal 7, but might no longer be needed.
    'themekit_container' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    'themekit_item_containers' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    'themekit_link_wrapper' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    'themekit_list' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
    'themekit_separator_list' => [
      'render element' => 'element',
      'file' => 'themekit.theme.inc',
    ],
  ];
}
