
# Key placeholders: $interface, $machine_name
ock_preset.preset.*.*:
  type: mapping
  label: 'OCK Presets'
  mapping:
    label:
      type: string
      label: 'Label setting machine name'
    conf:
      type: ignore
      label: 'ock_preset configuration'
