<?php
declare(strict_types=1);

use Drupal\ock_preset\Controller\Controller_IfacePresets;
use Drupal\ock_preset\ElementPreRender\ElementPreRender_ock_presetDrilldownContainer_PresetLink;

/**
 * Implements hook_element_info_alter().
 *
 * @param array $info
 */
function ock_preset_element_info_alter(array &$info): void {

  /* @see \Drupal\ock_preset\Element\RenderElement_DrilldownContainer */
  if (isset($info[$k = 'ock_preset_drilldown_container'])) {
    $info[$k]['#pre_render'][] = [ElementPreRender_ock_presetDrilldownContainer_PresetLink::class, 'preRender'];
  }
}

/**
 * @param array $element
 *
 * @return array
 */
function _ock_preset_ock_preset_drilldown_container_pre_render(array $element): array {

  if (!\Drupal::currentUser()->hasPermission('administer ock_preset')) {
    return $element;
  }

  $interface = $element['#ock_preset_interface'];

  $element['tools']['items'][] = [
    '#markup' => '<hr/>',
  ];

  $element['tools']['items']['ock_preset-link'] = [
    '#type' => 'link',
    '#title' => t('Create a preset'),
    '#url' => Controller_IfacePresets::route($interface)
      ->subpage('add')
      ->url(),
    '#attributes' => [
      // 'style' => 'display: none',
      'class' => ['ock_preset-link'],
      'target' => '_blank',
      'title' => t('Create a new preset with this plugin configuration.'),
    ],
  ];

  $element['#attached']['library'][] = 'ock_preset/drilldown-additions';

  return $element;
}
