name: CI Modules

on:
  - push

jobs:
  tests:
    name: Module tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        module:
          # Modules without tests are commented out.
          - ock
          - renderkit
          - service_discovery
          - themekit
        php: [8.3]
        composer-flags: ['', '--prefer-lowest']
        drupal-constraint: ['^11.0.5']

    defaults:
      run:
        working-directory: modules/${{ matrix.module }}

    steps:
      - uses: actions/checkout@v4

      # Prepare a local setup without ddev for regular tests.
      # This allows quick fails before any docker containers need to be pulled.
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # @todo Review which extensions are needed.
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Composer
        run: |
          set -x
          php --version

          # Add repositories for monorepo packages.
          # Use copy instead of symlink.
          # This way, the package will still be present in docker/ddev.
          composer config --merge --json repositories.0 '{"type": "path", "url": "../../packages/*", "options": {"symlink": false, "versions": {"*": "self.version"}}}'
          composer config --merge --json repositories.1 '{"type": "path", "url": "../*", "options": {"symlink": false, "versions": {"*": "self.version"}}}'

          # Expand composer.json as with ddev poser.
          export DRUPAL_CORE=${{ matrix.drupal-constraint }}
          curl -OL https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/scripts/expand_composer_json.php
          php expand_composer_json.php ${{ matrix.module }}
          rm -f expand_composer_json.php

          # Set some minimum versions for '--prefer-lowest'.
          composer require --no-update --dev composer/installers:^2
          composer require --no-update --dev open-telemetry/sdk:@stable
          composer require --no-update --dev masterminds/html5:^2.9.0

          # Disallow some plugins.
          composer config --no-plugins allow-plugins.php-http/discovery false
          composer config --no-plugins allow-plugins.tbachert/spi false

          # Apply composer flags.
          composer update --no-install ${{ matrix.composer-flags }}

          # Install composer packages.
          composer install --no-interaction

          # Run symlink_project.php
          curl -OL https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/scripts/symlink_project.php
          php symlink_project.php ${{ matrix.module }}
          rm -f symlink_project.php

      - name: DDEV - Setup
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: DDEV - Configure and start
        run: |
          set -x

          # Delete the top-level ddev directory, so ddev does not get confused.
          rm -rf ../../.ddev/

          ddev config \
            --project-type=drupal \
            --docroot=web \
            --php-version=${{ matrix.php }} \
            --project-name=demo
          ddev get ddev/ddev-drupal-contrib
          ddev get ddev/ddev-selenium-standalone-chrome
          ddev start
          ddev php --version

      - name: phpunit (DDEV)
        run: |
          set -x
          # Run tests need a browser.
          ddev phpunit \
            --fail-on-incomplete \
            --fail-on-warning \
            --fail-on-skipped \
            --fail-on-risky
