name: CI

on:
  - push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        composer-flags: ['', '--prefer-lowest']

    steps:
      - uses: actions/checkout@v4

      - name: DDEV - Setup
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: DDEV - Configure and start
        run: |
          set -x
          ddev config --php-version=${{ matrix.php }}
          ddev start

      - name: Composer
        run: |
          set -x
          ddev composer update --no-install ${{ matrix.composer-flags }}
          ddev composer install --prefer-dist --no-interaction

      - name: PhpUnit
        run: |
          set -x
          ddev exec ./vendor/bin/phpunit -vvv --debug \
            --fail-on-incomplete \
            --fail-on-warning \
            --fail-on-skipped \
            --fail-on-risky
