# Based on config suggested here:
# https://github.com/danharrin/monorepo-split-github-action
name: Split packages

on:
  push:
    branches:
      # @todo Decide to use either master or main.
      - main
      - master
      - '*.x'

    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          # - adaptism
          - class-discovery

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Split package ${{ matrix.package }}
        uses: "claudiodekker/splitsh-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
        with:
          prefix: "packages/${{ matrix.package }}"
          remote: "https://github.com/ock-php/${{ matrix.package }}.git"
          reference: "${{ github.ref_name }}"
          as_tag: "${{ startsWith(github.ref, 'refs/tags/') }}"
