# Based on config suggested here:
# https://github.com/danharrin/monorepo-split-github-action
name: Split packages

on:
  push:
    branches:
      - main
      - probe
      - '\d+\.x'
      - '\d+\.\d+\.x'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        include:
          - package: adaptism
          - package: class-discovery
          - { package: class-files-iterator, release: true}
          - package: codegen-tools
          - package: dependency-injection
          - package: di-discovery
          - package: egg
          - { package: helpers, release: true }
          - package: object-construction-kit
          - package: reflection
          - { package: reflector-aware-attributes, release: true}
          - package: testing

    steps:
      -
        # Push tags only to packages marked as 'release'.
        if: |
          !startsWith(github.ref, 'refs/tags/') || matrix.release

        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        # Push tags only to packages marked as 'release'.
        # This condition has to be repeated on every step.
        if: |
          !startsWith(github.ref, 'refs/tags/') || matrix.release

        name: Split package ${{ matrix.package }}
        uses: "claudiodekker/splitsh-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
        with:
          prefix: "packages/${{ matrix.package }}"
          remote: "https://github.com/ock-php/${{ matrix.package }}.git"
          reference: "${{ github.ref_name }}"
          as_tag: ${{ startsWith(github.ref, 'refs/tags/') }}
