# Based on config suggested here:
# https://github.com/danharrin/monorepo-split-github-action
name: Split modules

on:
  push:
    branches:
      - main
      - probe
      - '\d+\.x'
      - '\d+\.\d+\.x'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  modules_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { module: controller_attributes, release: true }

    steps:
      -
        # Push tags only to modules marked as 'release'.
        if: |
          !startsWith(github.ref, 'refs/tags/') || matrix.release

        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        # Push tags only to modules marked as 'release'.
        # This condition has to be repeated on every step.
        if: |
          !startsWith(github.ref, 'refs/tags/') || matrix.release

        name: Split module ${{ matrix.module }}
        uses: "claudiodekker/splitsh-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
        with:
          prefix: "modules/${{ matrix.module }}"
          remote: "https://github.com/ock-php/drupal-${{ matrix.module }}.git"
          reference: "${{ github.ref_name }}"
          as_tag: ${{ startsWith(github.ref, 'refs/tags/') }}
